name = "Iván Leis Mtnez."
description = "Periodista, antropólogo, tecnólogo"
keywords = "Iván Leis, periodista, journalist, prensa, etnografía, antropología, tecnología, empresa"
image = "jake.webp"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = "G-33WB8LVHR6"
base_url = "https://leisoes.github.io/jake"

[[sections]]
title = "Movies"
description = "Algunhas pelis"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Nightcrawler"
description = "A mesmerizing thriller delving into the dark world of crime journalism"
url = "https://www.imdb.com/title/tt2872718/"
[[sections.items]]
title = "Brokeback Mountain"
description = "A groundbreaking romantic drama challenging societal expectations"
url = "https://www.imdb.com/title/tt0388795/"
[[sections.items]]
title = "Prisoners"
description = "A gripping thriller entangling a detective in a web of secrets during a kidnapping investigation"
url = "https://www.imdb.com/title/tt1392214/"

[[sections]]
title = "Links"
description = "Saiba mais nestes enlaces"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Hemeroteca persoal"
url = "https://blog.ivanleis.eu"
[[sections.items]]
title = "Notas musicais"
url = "https://sona.ivanleis.eu"
[[sections.items]]
title = "Zen&Taichi"
url = "https://dojo.ivanleis.eu"
[[sections.items]]
title = "Servizos"
url = "https://glances.ileis.myds.me"
